name: Pull Request Stats
run-name: Pull Request Ben
on:
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: Repo1/pull-request-stats@master
